/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewSession_idRouteImport } from './routes/interview.$session_id'
import { Route as AdminReportSessionIdRouteImport } from './routes/admin_.report.$sessionId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSession_idRoute = InterviewSession_idRouteImport.update({
  id: '/interview/$session_id',
  path: '/interview/$session_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportSessionIdRoute = AdminReportSessionIdRouteImport.update({
  id: '/admin_/report/$sessionId',
  path: '/admin/report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/interview/$session_id': typeof InterviewSession_idRoute
  '/admin/report/$sessionId': typeof AdminReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/interview/$session_id': typeof InterviewSession_idRoute
  '/admin/report/$sessionId': typeof AdminReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/interview/$session_id': typeof InterviewSession_idRoute
  '/admin_/report/$sessionId': typeof AdminReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/interview/$session_id' | '/admin/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/interview/$session_id' | '/admin/report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/interview/$session_id'
    | '/admin_/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  InterviewSession_idRoute: typeof InterviewSession_idRoute
  AdminReportSessionIdRoute: typeof AdminReportSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$session_id': {
      id: '/interview/$session_id'
      path: '/interview/$session_id'
      fullPath: '/interview/$session_id'
      preLoaderRoute: typeof InterviewSession_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/report/$sessionId': {
      id: '/admin_/report/$sessionId'
      path: '/admin/report/$sessionId'
      fullPath: '/admin/report/$sessionId'
      preLoaderRoute: typeof AdminReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  InterviewSession_idRoute: InterviewSession_idRoute,
  AdminReportSessionIdRoute: AdminReportSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
